version: '3.9'

services:
  mongo_db:
    container_name: mongo_container
    image: "mongo:4.4.7"
    hostname: mongo_db_host
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - backend

  backend_api:
    container_name: backend_api_container
    image: victorvsm/backend_api:1.0
    env_file:
      - .env
    environment:
      - MONGO_URI=mongo_db
      - MAIL_LOGIN=${MAIL_LOGIN}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    ports:
      - 4000:8080
    depends_on:
      - mongo_db
    networks:
      - backend

networks:
  backend:
    external: false
    name: backend
